### ISSUE TITLE
CLOSED-CAPTIONS is added in Version 6

### ISSUE THREAD

**Issue by lxb200709** [grafov/m3u8#106]
CLOSED-CAPTIONS is added in Version 6, does it need a method for CLOSED-CAPTIONS to set version to v6? @mbowBC

**Comment by bradleyfalzon** [comment]
I'm not convinced whether it's required, section 7 appears to outline the expectations: https://tools.ietf.org/html/rfc8216#section-7

If we increase the version because closed captions were supported, any older players would not be able to play the stream - just because a tag existed that it isn't critical to playback.

**Comment by lxb200709** [comment]
Actually, my bad. I think I misunderstood the version 6.  It actually adds the CLOSED-CAPTIONS for #EXT-X-MEDIA, which can be included in video renditions. e.g:
#EXT-X-MEDIA:TYPE=CLOSED-CAPTIONS,GROUP-ID="cc",LANGUAGE="en",NAME="English",DEFAULT=YES,AUTOSELECT=YES,INSTREAM-ID="CC1"

#EXT-X-STREAM-INF:AVERAGE-BANDWIDTH=2190673,BANDWIDTH=2523597,CODECS="avc1.640020,mp4a.40.2",RESOLUTION=960x540,FRAME-RATE=60.000,CLOSED-CAPTIONS="cc",AUDIO="a1",SUBTITLES="sub1"
v5/prog_index.m3u8
