### ISSUE TITLE
encode(boolean) doesn't exist

### ISSUE THREAD

**Issue by kaihendry** [grafov/m3u8#88]
fmt.Println(p.Encode(true).String())

Further when I print a playlist I've modified, it's printing the original. I'm confused.

UPDATE: Discovered I need to use https://godoc.org/github.com/grafov/m3u8#MasterPlaylist.ResetCache ... But why ?!

**Comment by bradleyfalzon** [comment]
You'll need to reset the cache each time you modify the playlist and call `Encode()` or `String()`. We cache these playlists internally for performance reasons, so if you need to encode the playlist multiple times, we only need to do it once (if the playlist hasn't been updated).

But note, any of the methods we provide, such as Append, should already be resetting the cache. I have a pretty large use of this library, and don't need to call `ResetCache()` because all the methods handle this for me.

Also `fmt.Println(p.Encode().String())` can just be written as `fmt.Println(p.String())` as the `String()` method already calls `Encode()` internally.

I'll close this issue, but feel free to reopen and comment if this doesn't quite answer the question, or a cache isn't being reset when you think it should.
